id: PBF441BE0
initial_creation_type: input
source_metadata:
  title: Parting from the Four Attachments
  language: de
  description: 'A series of texts related to the famous four-line instruction that
    Sachen Kunga Nyingpo (1092–1158) received from Mañjuśrī:'
  volume:
    547fdb4ff28944d99102a92b8688509f:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    097b69347779477f97c5b35871658eb4:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Lineage Prayers
    6598769a0bf5474caf76ad2481b2ee8f:
      title: The Instructions on Parting from the Four Attachments
      parent: Root Text
    5080cdefb3dd4b52b16c010ab7c8135d:
      title: Parting from the Four Attachments
      parent: Commentaries
    28d33113205246d491270f83fc841e03:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Commentaries
    01a0631f498540f785352e9a8c781d05:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Commentaries
    b21548154b174225b2753c9d3573f1b2:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Song
created_at: '2022-03-01T05:02:13.480967'
last_modified_at: '2022-03-01T05:02:13.480970'
